image: drupalpod/drupalpod-gitpod-base:20221021

tasks:
  - name: typo3
    init: |
      ddev start -y
      ddev composer install
      ddev snapshot restore --latest
      ddev pnpm install
    command: |
      ddev start -y
      gp sync-done prepare
      gp ports await 8080 && gp preview $(gp url 8080)

  - name: vite
    command: |
      gp sync-await prepare
      ddev vite-serve start

ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  # Used by projector
  - port: 6942
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore
  # projector port
  - port: 9999
    onOpen: open-browser

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true